/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rushi;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.animation.timing.Animator;

/**
 *
 * @author Rushikesh Bhondave
 */
public class Login_Page extends javax.swing.JFrame {

   private Animator animatorLogin;
    private Animator animatorBody;
    private boolean signIn;
    private final String user="root";
    private final  String pass="Rushikesh@5046";
    private final  String sqlcon="jdbc:mysql://localhost:3306/rushi"; 
   Connection con=null;
   PreparedStatement pst =null;
   ResultSet rs=null;   
    
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background11 = new com.company.Background1();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Username1 = new com.mycompany.rushi.TextField();
        Password1 = new com.mycompany.rushi.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Account_Type1 = new javax.swing.JComboBox<>();
        Clear3 = new javax.swing.JButton();
        create_Account = new javax.swing.JLabel();
        Sign_Up = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 102, 0))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-login-45.png"))); // NOI18N

        Username1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Username1.setLabelText("Username");

        Password1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Password1.setLabelText("Password");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-forgot-password-40.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-choose-40.png"))); // NOI18N

        Account_Type1.setBackground(new java.awt.Color(255, 255, 255));
        Account_Type1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Account_Type1.setForeground(new java.awt.Color(204, 204, 204));
        Account_Type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Type", "Admin", "Seller", "User", " " }));
        Account_Type1.setToolTipText("Account Typee");

        Clear3.setBackground(new java.awt.Color(188, 237, 105));
        Clear3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Clear3.setForeground(new java.awt.Color(255, 255, 255));
        Clear3.setText("Clear");
        Clear3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Clear3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Clear3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Clear3MouseExited(evt);
            }
        });
        Clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear3ActionPerformed(evt);
            }
        });

        create_Account.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        create_Account.setForeground(new java.awt.Color(153, 153, 255));
        create_Account.setText("Don't have not an account?...");
        create_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_AccountMouseClicked(evt);
            }
        });

        Sign_Up.setBackground(new java.awt.Color(188, 237, 105));
        Sign_Up.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Sign_Up.setForeground(new java.awt.Color(255, 255, 255));
        Sign_Up.setText("Sign Up");
        Sign_Up.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Sign_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_UpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sign_UpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Sign_UpMouseExited(evt);
            }
        });
        Sign_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_UpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Sign_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Account_Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create_Account))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account_Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sign_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(create_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit-41.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background11Layout = new javax.swing.GroupLayout(background11);
        background11.setLayout(background11Layout);
        background11Layout.setHorizontalGroup(
            background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background11Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        background11Layout.setVerticalGroup(
            background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background11Layout.createSequentialGroup()
                .addGroup(background11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background11Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(background11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Clear3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear3MouseClicked
          Clear3.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_Clear3MouseClicked

    private void Clear3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear3MouseEntered
         Clear3.setBackground(new Color(16, 71, 101));
    }//GEN-LAST:event_Clear3MouseEntered

    private void Clear3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear3MouseExited
        Clear3.setBackground(new Color(188,237,105));
    }//GEN-LAST:event_Clear3MouseExited

    private void Clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear3ActionPerformed
       Username1.setText("");
       Password1.setText("");
       Account_Type1.setSelectedIndex(0);
    }//GEN-LAST:event_Clear3ActionPerformed

    private void create_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_AccountMouseClicked
        setVisible(false);
        new KCreate_Page().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_create_AccountMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Sign_UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_UpMouseClicked
    Sign_Up.setBackground(new Color(0,84,104));
    }//GEN-LAST:event_Sign_UpMouseClicked

    private void Sign_UpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_UpMouseEntered
   Sign_Up.setBackground(new Color(16, 71, 101));
    }//GEN-LAST:event_Sign_UpMouseEntered

    private void Sign_UpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_UpMouseExited
           Sign_Up.setBackground(new Color(188,237,105));
    }//GEN-LAST:event_Sign_UpMouseExited

    private void Sign_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_UpActionPerformed
       String username=Username1.getText().trim();

        String password=Password1.getText().trim();

        String Account_Type=Account_Type1.getSelectedItem().toString();

        if(username.isEmpty()||password.isEmpty()||username.isBlank()||password.isBlank()|| Account_Type.isBlank())
        {
            JOptionPane.showMessageDialog(rootPane, "Please Insert The Data", "Failure",JOptionPane.ERROR_MESSAGE);
        }

        if(Account_Type1.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select The Account Type", "Failure",JOptionPane.ERROR_MESSAGE);
        }
        else if (!username.matches("[a-zA-Z0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Please Insert Correct Username...", "failure", JOptionPane.ERROR_MESSAGE);                                                                                                                                                                  //  data valdition cheak
            Username1.setText("");
            Username1.grabFocus();
        }
        else if (!password.matches("[a-zA-Z0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Please Insert Correct Username...", "failure", JOptionPane.ERROR_MESSAGE);                                                                                                                                                                  //  data valdition cheak
            Password1.setText("");
            Password1.grabFocus();
        }
        else
        {
            try
            {

                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(sqlcon, user, pass);
                Statement pss = con.createStatement();   // create_Username,create_Passworrd,create_Account_Type

                rs = pss.executeQuery(" select * from rushi.create_account  where create_Username=?  create_Passworrd=?  create_Account_Type=?;");   

                if (rs.next()==false)
                {
                    JOptionPane.showMessageDialog(rootPane, "Account is  not found...", "failure", JOptionPane.ERROR_MESSAGE);

                }
                else
                {
                    pst.setString(1, username);
                    pst.setString(2,password);
                    pst.setString(3,Account_Type);
                    setVisible(false)  ;
                    new Main_Page().setVisible(rootPaneCheckingEnabled);
                }
            }
            catch (ClassNotFoundException | SQLException e)
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "There is issue ........", "Failure",JOptionPane.ERROR_MESSAGE);

            }
//            finally
//            {
//                if (pst != null)
//                {
//                    try
//                    {
//                        pst.close();
//                    }
//                    catch (SQLException e)
//                    {
//                        e.printStackTrace();
//                    }
//                }
//
//                if (pst != null)
//                {
//                    try
//                    {
//                        con.close();
//                    }
//                    catch (SQLException e)
//                    {
//                        e.printStackTrace();
//                    }
//                }
//            }
        }

    }//GEN-LAST:event_Sign_UpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Account_Type1;
    private javax.swing.JButton Clear3;
    private com.mycompany.rushi.TextField Password1;
    private javax.swing.JButton Sign_Up;
    private com.mycompany.rushi.TextField Username1;
    private com.company.Background1 background11;
    private javax.swing.JLabel create_Account;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
